defaults:
  - data: radar_echo_return_simple_shapes
  - task: classification
  - hydra: default
  - _self_
  - model: lstm

note: ""

iteration: 1

n_classes: 4

test_method: cluster_sinusoid
#test_method: random_dropouts
#test_method: subsample
#test_method: percentile_saturation

# Define a map of model types to their respective paths
# TODO: Update the paths to the trained models
model_paths:
  lstm_vanilla: "insert path here"
  lstm_bidirectional: "insert path here"
  mlp: "insert path here"
  transformer: "insert path here"
  residual_network: "insert path here"
  informer: "insert path here"

seed: 330159533758566588472678076910300130992

wandb:
  id: ~
  entity: space_debri
  project: Robustness_${test_method}
  group: ${model.name}
  mode: online
  name: ${model.name}_run=${iteration}
hydra:
  job:
    name: ${wandb.group}

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  max_epochs: 10
  log_every_n_steps: 10
  val_check_interval: 0.5

early_stopping: 6
