defaults:
  - data: radar_echo_return_simple_shapes
  - task: classification
  - hydra: default
  # Allow the model to overwrite the settings below
  - _self_
  - model: lstm

note: ""

save_model: true
log_model_to_wandb: true

seed: 330159533758566588472678076910300130992
eval_testset: true

wandb:
  id: ~
  entity: ~ 
  project: ~
  group: ~
  mode: ~
  name: ~

hydra:
  job:
    name: ${wandb.group}

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  max_epochs: 30
  log_every_n_steps: 10
  val_check_interval: 0.5

early_stopping: 10
